baseURL = "https://www.jrhoun.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "JR Houn"
title = "Grace and Generativity"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "Copyright © 2020 JR Houn | Built using the [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-167412742-1"
disqusShortname = "jrhoun"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["blog","podcast","personal","generativity"]

	# Add meta description in head part
	description = "Finding a way forward with words, music, and empathy."

	# Add pagetitle to homepage <title> tag
	pagetitle = "Finding a way forward with words, music, and empathy."

	# Add a subtitle to your website
	subtitle = "Finding a way forward with words, music, and empathy."

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/jrhoun.png"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
  mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
# name = "Categories"
# url = "/categories"
# weight = 5

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
url = "mailto:jr.houn@gmail.com"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/jrhoun"

[[params.social]]
name = "YouTube"
icon = "fab fa-youtube"
url = "https://youtube.com/whoisdallas"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/jrhoun"

[[params.social]]
name = "Ko-Fi"
icon = "fas fa-coffee"
url = "https://ko-fi.com/jrhoun"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
