[build]
publish = "public"
command = "chmod +x scripts/*.sh && ./scripts/decrypt-photos.sh && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.88.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/protected/*"
  status = 200
  conditions = {Role = ["admin", "visitor"]}

[[redirects]]
  from = "/protected/*"
  to = "/login"
  status = 401
  force = true

[[redirects]]
  from = "/img/protected/*"
  status = 200
  conditions = {Role = ["admin", "visitor"]}

[[redirects]]
  from = "/img/protected/*"
  to = "/login"
  status = 401
  force = true
